spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres

spring.datasource.username=postgres.hhkojqawniuyuiqmprvn

spring.datasource.password=${SUPABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=info.conclave2026@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

supabase.url=https://hhkojqawniuyuiqmprvn.supabase.co
supabase.bucket=passes
supabase.service-key=${SKEY}